version: '3.7'

services:
  frontend:
    build:
      context: ./src/frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
  backend:
    build:
      context: ./src/backend
    ports:
      - '8000:8000'