version: '3.7'

services:
  frontend:
    build:
      context: ./src/frontend
      args: 
        BACKEND_HOST: localhost
        BACKEND_PORT: '8000'
    ports:
      - '3000:80'
    depends_on:
      - backend
  backend:
    build:
      context: ./src/backend
    ports:
      - '8000:8000'
    environment:
      BACKEND_HOST: '0.0.0.0'
      BACKEND_PORT: '8000'