name: Publish Docker Images to GitHub Docker Registory
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: backend
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mizukmb/diary.mizukmb.net/backend
          username: mizukmb
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          workdir: src/backend
      - name: frontend
        env:
          NPM_RUN_COMMAND: prod
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mizukmb/diary.mizukmb.net/frontend
          username: mizukmb
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          workdir: src/frontend
          buildargs: NPM_RUN_COMMAND
